version: "3.9"
services:
  grafana:
    container_name: grafana
    restart: always
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    image: grafana/grafana:8.0.6
    volumes:
      - grafana-data:/var/lib/grafana
#    ports:
#      - "3000:3000"
    network_mode: "host"
  #    networks:
#      - main

  prometheus:
    container_name: prometheus
    restart: always
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml 
    image: prom/prometheus
    network_mode: "host"
#    networks:
#      - main

#networks:
#  main:
#    name: "main"

volumes:
  prometheus-data:
  grafana-data: 

